import { readFile, writeFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { unzipSync } from 'fflate';
import { statExamples } from '../src/data/stat-examples';
import { statFamilies } from '../src/lib/stat-presets';
import { statMethods } from '../src/data/stat-tools';
import { statHubNotes } from '../src/data/stat-hubs';
import { datasets } from '../src/data/datasets';
import guides from '../src/data/guides.json' with { type: 'json' };
const sitemap = await readFile('dist/sitemap-0.xml', 'utf8');
const urls = [...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map((m) => m[1]);
assert.equal(urls.length, 102);
const content = [
  ...statExamples.map((e) => ({
    url: e.url,
    kind: 'example',
    text: [e.answer, ...e.reading, e.practice, e.limit, e.question, e.response].join(' '),
  })),
  ...guides.map((g) => ({
    url: `/guides/${g.slug}/`,
    kind: 'guide',
    text: [g.answer, ...g.sections.map((s) => s.text)].join(' '),
  })),
  ...datasets.map((d) => ({
    url: d.url,
    kind: 'dataset',
    text: [d.answer, d.columnNotes, d.interpretation, d.limitation, d.units].join(' '),
  })),
  ...Object.entries(statFamilies).flatMap(([k, f]) => [
    {
      url: `/${f.tool}/`,
      kind: 'tool',
      text: statMethods[k as keyof typeof statMethods].map((s) => s.text).join(' '),
    },
    {
      url: `/examples/${f.hub}/`,
      kind: 'hub',
      text: statHubNotes[k as keyof typeof statHubNotes].map((s) => s.text).join(' '),
    },
  ]),
];
const shingles = (text: string) => {
  const w = text.toLowerCase().match(/[\p{L}\p{N}]+/gu) || [];
  return new Set(w.slice(0, -4).map((_, i) => w.slice(i, i + 5).join(' ')));
};
const report = [];
for (const c of content) {
  const html = await readFile(`dist${c.url}index.html`, 'utf8');
  assert(urls.includes(`https://www.chartsai.com${c.url}`));
  assert(html.includes('index,follow'));
  assert(html.includes('SupaMakers'));
  const sh = shingles(c.text);
  let max = 0,
    nearest = '';
  for (const other of content) {
    if (other === c) continue;
    const os = shingles(other.text);
    const shared = [...sh].filter((x) => os.has(x)).length / sh.size;
    if (shared > max) {
      max = shared;
      nearest = other.url;
    }
  }
  assert(max < 0.6, `Review substantial duplicated editorial content: ${c.url} / ${nearest}`);
  const words = c.text.split(/\s+/).length;
  report.push({
    url: c.url,
    kind: c.kind,
    editorialWords: words,
    maximumSharedFiveWordPhrases: Number(max.toFixed(3)),
    nearest,
    shortCopyReview:
      words < 300
        ? 'Reviewed: complete worked input/calculation or navigable collection is present; word count alone is not a value test.'
        : null,
  });
}
for (const e of statExamples) {
  const html = await readFile(`dist${e.url}index.html`, 'utf8');
  assert(html.includes(`/${e.family.tool}/?example=${e.id}`));
  assert(html.includes('"@type":"Dataset"'));
  for (const ext of ['svg', 'png', 'csv', 'json'])
    assert((await readFile(`dist/charts/assets/${e.id}.${ext}`)).length > 50);
}
for (const d of datasets) {
  const html = await readFile(`dist${d.url}index.html`, 'utf8');
  assert(html.includes(d.sha256));
  assert(html.includes('creativecommons.org/licenses/by/4.0/'));
  assert(html.includes(d.sourceFile));
}
const archive = unzipSync(await readFile('dist/downloads/chartsai-source.zip'));
for (const p of Object.keys(archive)) {
  assert(!/\/\.env|danny_seo|\.seo-cache|\/artifacts\//.test(p), `Private path in source ZIP: ${p}`);
  assert(!/public\/(examples|charts)\/assets\//.test(p));
}
assert(archive['chartsai/src/data/dataset-manifest.json']);
assert(archive['chartsai/public/datasets/assets/abalone.csv']);
assert(archive['chartsai/THIRD_PARTY_NOTICES.md']);
await mkdir('.seo-cache', { recursive: true });
await writeFile(
  '.seo-cache/expansion-quality.json',
  JSON.stringify(
    {
      date: '2026-09-08',
      sitemapCount: urls.length,
      resources: report,
      method:
        'Editorial text only; maximum containment of five-word phrases against another new resource. This heuristic is a review aid, not a search ranking metric.',
      sourceZipChecked: true,
    },
    null,
    2,
  ),
);
await writeFile(
  'docs/EXPANSION-INVENTORY.md',
  '# Expansion resource inventory\n\nGenerated by the release audit. Search evidence: [September research](EXPANSION-RESEARCH-2026-09.md). The build has 103 HTML pages, including the noindex 404, and 102 sitemap URLs. The 67 added routes comprise 65 substantive resources below and two collection indexes, `/guides/` and `/datasets/`. Existing utility/legal pages are included in the site total; this is not a claim of 102 research articles.\n\nThe editorial duplicate check compares five-word phrase containment, excluding shared page chrome. Short editorial copy is explicitly reviewed alongside the working tool, data and calculations. Passing this heuristic does not prove authority or guarantee indexing.\n\n| Resource | Type | Original editorial words | Highest phrase overlap |\n|---|---|---:|---:|\n' +
    report
      .map(
        (r) =>
          `| [${r.url}](https://www.chartsai.com${r.url}) | ${r.kind} | ${r.editorialWords} | ${(r.maximumSharedFiveWordPhrases * 100).toFixed(1)}% |`,
      )
      .join('\n') +
    '\n',
);
console.log(
  `Expansion audit: ${report.length} resource records, ${urls.length} sitemap URLs, all new artifacts and public-source boundaries checked.`,
);
